import type { NextPage } from "next";
import Head from "next/head";
import { ActionButton } from "@nation3/components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ActionButton
          className="btn btn-primary normal-case font-medium grow"
          action={{ writeAsync: async () => {} }}
        >
          ActionButton
        </ActionButton>
      </main>
    </div>
  );
};

export default Home;
